import MainNavigation from "@/components/navigation/MainNavigation";
import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-700">
        <MainNavigation></MainNavigation>
        <main>{children}</main>
      </body>
    </html>
  );
}
