import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RootLink from "@/components/RootLink";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const data = await fetch('http://localhost:8080/ar');
  console.log(await data.json())
  console.log('layout')
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RootLink></RootLink>
        {children}
      </body>
    </html>
  );
}
